--- 
abstract: A CPANPLUS GUI Shell written in wxWidgets
author: Skaman Sam Tyler <skamansam@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CPANPLUS-Shell-Wx
no_index: 
  directory: 
    - blib
    - inc
    - t
requires: 
  Archive::Extract: 0.0
  CPANPLUS: 0.076
  Class::Struct: 0.0
  Config: 0.0
  File::Fetch: 0.0
  File::HomeDir: 0.0
  File::Temp: 0.0
  IPC::Cmd: 0.0
  LWP::Simple: 0.0
  Locale::Maketext::Simple: 0.0
  Log::Message: 0.0
  Module::Load: 0.0
  Module::Load::Conditional: 0.0
  Module::Loaded: 0.0
  Object::Accessor: 0.0
  Package::Constants: 0.0
  Params::Check: 0.0
  Term::UI: 0.0
  URI::Escape: 0.0
  Wx: 0.74
  YAML: 0.0
  perl: 5.005
version: 0.03
