#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.1 on Thu Mar 20 08:04:49 2008
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;

package wxFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: wxFrame::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	

	# Menu Bar

	$self->{themenubar} = Wx::MenuBar->new();
	my $wxglade_tmp_menu;
	$self->{file_menu} = Wx::Menu->new();
	$self->{file_quit_menu} = $self->{file_menu}->Append(file_quit_menu, "Quit", "Quit");
	$self->{themenubar}->Append($self->{file_menu}, "File");
	$self->SetMenuBar($self->{themenubar});
	
# Menu Bar end

	$self->{thestatusbar} = $self->CreateStatusBar(1, wxST_SIZEGRIP);
	
# Tool Bar
	$self->{thetoolbar} = Wx::ToolBar->new($self, -1, wxDefaultPosition, wxDefaultSize, wxTB_HORIZONTAL|wxTB_3DBUTTONS|wxTB_TEXT);
	$self->SetToolBar($self->{thetoolbar});
	$self->{thetoolbar}->AddTool(quit_tb, "Quit", wxNullBitmap, wxNullBitmap, wxITEM_NORMAL, "Quit", "Quit");
	# Tool Bar end

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: wxFrame::__set_properties

	$self->SetTitle("wxCPANPLUS");
	$self->{thestatusbar}->SetStatusWidths(-1);
	
	my( @thestatusbar_fields ) = (
		"Welcome to wxCPANPLUS!"
	);

	if( @thestatusbar_fields ) {
		$self->{thestatusbar}->SetStatusText($thestatusbar_fields[$_], $_) 	
		for 0 .. $#thestatusbar_fields ;
	}
	$self->{thetoolbar}->SetToolBitmapSize(wxSIZE(16, 15));
	$self->{thetoolbar}->SetMargins(0, 0);
	$self->{thetoolbar}->Realize();

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: wxFrame::__do_layout

	$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
	$self->SetSizer($self->{sizer_1});
	$self->{sizer_1}->Fit($self);
	$self->Layout();

# end wxGlade
}

# end of class wxFrame

1;

1;

package main;

unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $app = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $mainWindow = wxFrame->new();

	$app->SetTopWindow($mainWindow);
	$mainWindow->Show(1);
	$app->MainLoop();
}
